name: APAutoNPC
version: ${projectVersion}
main: net.apdevteam.apautonpc.APAutoNPC
api-version: 1.20
authors: [TylerS1066, _MrUniverse, APDevTeam]
depend: [WorldGuard, WorldEdit, Vault, Citizens, dtlTraders]
commands:
  buynpc:
    description: Purchase a NPC
    usage: /buynpc <type>
    permission: apautonpc.buy
  sellnpc:
    description: Sell a NPC
    usage: /sellnpc <type>
    permission: apautonpc.sell
