name: APAutoNPC
main: ap.autonpc.apdevteamuni
version: 2.0.1
authors: [_MrUniverse, APDevTeam]
depend: [WorldGuard, WorldEdit, Vault, Citizens, Sentinel]
commands: 
    autonpc:
        description: Spawns in a NPC
        usage: /<command> <type>
        permission: apautonpc.use