
name: Java CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Stage jar
      run: mkdir staging && cp target/APAutoNPC*.jar staging && mv staging/APAutoNPC*.jar staging/APAutoNPC_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v3
      with:
        name: APAutoNPC_Dev-Build
        path: staging/APAutoNPC_*.jar
